In [1]:
import numpy as np
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [2]:
a[-1]

np.int64(4)

In [2]:
import numpy as np
b=np.array([1,2,3,4,5,6,7,8,9])
b[0:9]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
b=np.array([1,2,3,4,5,6,7,8,9])
b[-1:5]

array([], dtype=int64)

In [4]:
c=b.copy()
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
d=b.view()
d

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
b[0]=12
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
d

array([12,  2,  3,  4,  5,  6,  7,  8,  9])

In [9]:
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
b=a.reshape(4,3)
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [10]:
c=np.array([13,14,15])
d=np.concatenate((a,c))
np.array_split(d,2)

[array([1, 2, 3, 4, 5, 6, 7, 8]), array([ 9, 10, 11, 12, 13, 14, 15])]

In [11]:
np.where(d==4)

(array([3]),)

In [12]:
np.where(d%2==0)

(array([ 1,  3,  5,  7,  9, 11, 13]),)

In [13]:
c=np.array([3,4,2,10,5])
np.sort(c)

array([ 2,  3,  4,  5, 10])

In [14]:
c=np.array([[2,3,1,6],[5,1,2,4]])
np.sort(c)

array([[1, 2, 3, 6],
       [1, 2, 4, 5]])

In [15]:
c=np.array(['apple','orange','banana','mango'])
np.sort(c)


array(['apple', 'banana', 'mango', 'orange'], dtype='<U6')

In [16]:
np.random.randint(100)

3

In [17]:
np.random.rand(10)

array([0.34437647, 0.60863848, 0.05284261, 0.19558762, 0.19587695,
       0.41285625, 0.26595457, 0.32822311, 0.38466062, 0.96016251])

In [18]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [19]:
np.ones(2)

array([1., 1.])

In [20]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])